INSERT INTO tbl_timezones (identifier, description) VALUES ('Pacific/Midway', '(GMT-11:00) Midway Island');
INSERT INTO tbl_timezones (identifier, description) VALUES ('US/Samoa', '(GMT-11:00) Samoa');
INSERT INTO tbl_timezones (identifier, description) VALUES ('US/Hawaii', '(GMT-10:00) Hawaii');
INSERT INTO tbl_timezones (identifier, description) VALUES ('US/Alaska', '(GMT-09:00) Alaska');
INSERT INTO tbl_timezones (identifier, description) VALUES ('US/Pacific', '(GMT-08:00) Pacific Time (US &amp; Canada)');
INSERT INTO tbl_timezones (identifier, description) VALUES ('America/Tijuana', '(GMT-08:00) Tijuana');
INSERT INTO tbl_timezones (identifier, description) VALUES ('US/Arizona', '(GMT-07:00) Arizona');
INSERT INTO tbl_timezones (identifier, description) VALUES ('US/Mountain', '(GMT-07:00) Mountain Time (US &amp; Canada)');
INSERT INTO tbl_timezones (identifier, description) VALUES ('America/Chihuahua', '(GMT-07:00) Chihuahua');
INSERT INTO tbl_timezones (identifier, description) VALUES ('America/Mazatlan', '(GMT-07:00) Mazatlan');
INSERT INTO tbl_timezones (identifier, description) VALUES ('America/Mexico_City', '(GMT-06:00) Mexico City');
INSERT INTO tbl_timezones (identifier, description) VALUES ('America/Monterrey', '(GMT-06:00) Monterrey');
INSERT INTO tbl_timezones (identifier, description) VALUES ('Canada/Saskatchewan', '(GMT-06:00) Saskatchewan');
INSERT INTO tbl_timezones (identifier, description) VALUES ('US/Central', '(GMT-06:00) Central Time (US &amp; Canada)');
INSERT INTO tbl_timezones (identifier, description) VALUES ('US/Eastern', '(GMT-05:00) Eastern Time (US &amp; Canada)');
INSERT INTO tbl_timezones (identifier, description) VALUES ('US/East-Indiana', '(GMT-05:00) Indiana (East)');
INSERT INTO tbl_timezones (identifier, description) VALUES ('America/Bogota', '(GMT-05:00) Bogota');
INSERT INTO tbl_timezones (identifier, description) VALUES ('America/Lima', '(GMT-05:00) Lima');
INSERT INTO tbl_timezones (identifier, description) VALUES ('America/Caracas', '(GMT-04:30) Caracas');
INSERT INTO tbl_timezones (identifier, description) VALUES ('Canada/Atlantic', '(GMT-04:00) Atlantic Time (Canada)');
INSERT INTO tbl_timezones (identifier, description) VALUES ('America/La_Paz', '(GMT-04:00) La Paz');
INSERT INTO tbl_timezones (identifier, description) VALUES ('America/Santiago', '(GMT-04:00) Santiago');
INSERT INTO tbl_timezones (identifier, description) VALUES ('Canada/Newfoundland', '(GMT-03:30) Newfoundland');
INSERT INTO tbl_timezones (identifier, description) VALUES ('America/Buenos_Aires', '(GMT-03:00) Buenos Aires');
INSERT INTO tbl_timezones (identifier, description) VALUES ('Greenland', '(GMT-03:00) Greenland');
INSERT INTO tbl_timezones (identifier, description) VALUES ('Atlantic/Stanley', '(GMT-02:00) Stanley');
INSERT INTO tbl_timezones (identifier, description) VALUES ('Atlantic/Azores', '(GMT-01:00) Azores');
INSERT INTO tbl_timezones (identifier, description) VALUES ('Atlantic/Cape_Verde', '(GMT-01:00) Cape Verde Is.');
INSERT INTO tbl_timezones (identifier, description) VALUES ('Africa/Casablanca', '(GMT) Casablanca');
INSERT INTO tbl_timezones (identifier, description) VALUES ('Europe/Dublin', '(GMT) Dublin');
INSERT INTO tbl_timezones (identifier, description) VALUES ('Europe/Lisbon', '(GMT) Lisbon');
INSERT INTO tbl_timezones (identifier, description) VALUES ('Europe/London', '(GMT) London');
INSERT INTO tbl_timezones (identifier, description) VALUES ('Africa/Monrovia', '(GMT) Monrovia');
INSERT INTO tbl_timezones (identifier, description) VALUES ('Europe/Amsterdam', '(GMT+01:00) Amsterdam');
INSERT INTO tbl_timezones (identifier, description) VALUES ('Europe/Belgrade', '(GMT+01:00) Belgrade');
INSERT INTO tbl_timezones (identifier, description) VALUES ('Europe/Berlin', '(GMT+01:00) Berlin');
INSERT INTO tbl_timezones (identifier, description) VALUES ('Europe/Bratislava', '(GMT+01:00) Bratislava');
INSERT INTO tbl_timezones (identifier, description) VALUES ('Europe/Brussels', '(GMT+01:00) Brussels');
INSERT INTO tbl_timezones (identifier, description) VALUES ('Europe/Budapest', '(GMT+01:00) Budapest');
INSERT INTO tbl_timezones (identifier, description) VALUES ('Europe/Copenhagen', '(GMT+01:00) Copenhagen');
INSERT INTO tbl_timezones (identifier, description) VALUES ('Europe/Ljubljana', '(GMT+01:00) Ljubljana');
INSERT INTO tbl_timezones (identifier, description) VALUES ('Europe/Madrid', '(GMT+01:00) Madrid');
INSERT INTO tbl_timezones (identifier, description) VALUES ('Europe/Paris', '(GMT+01:00) Paris');
INSERT INTO tbl_timezones (identifier, description) VALUES ('Europe/Prague', '(GMT+01:00) Prague');
INSERT INTO tbl_timezones (identifier, description) VALUES ('Europe/Rome', '(GMT+01:00) Rome');
INSERT INTO tbl_timezones (identifier, description) VALUES ('Europe/Sarajevo', '(GMT+01:00) Sarajevo');
INSERT INTO tbl_timezones (identifier, description) VALUES ('Europe/Skopje', '(GMT+01:00) Skopje');
INSERT INTO tbl_timezones (identifier, description) VALUES ('Europe/Stockholm', '(GMT+01:00) Stockholm');
INSERT INTO tbl_timezones (identifier, description) VALUES ('Europe/Vienna', '(GMT+01:00) Vienna');
INSERT INTO tbl_timezones (identifier, description) VALUES ('Europe/Warsaw', '(GMT+01:00) Warsaw');
INSERT INTO tbl_timezones (identifier, description) VALUES ('Europe/Zagreb', '(GMT+01:00) Zagreb');
INSERT INTO tbl_timezones (identifier, description) VALUES ('Europe/Athens', '(GMT+02:00) Athens');
INSERT INTO tbl_timezones (identifier, description) VALUES ('Europe/Bucharest', '(GMT+02:00) Bucharest');
INSERT INTO tbl_timezones (identifier, description) VALUES ('Africa/Cairo', '(GMT+02:00) Cairo');
INSERT INTO tbl_timezones (identifier, description) VALUES ('Africa/Harare', '(GMT+02:00) Harare');
INSERT INTO tbl_timezones (identifier, description) VALUES ('Europe/Helsinki', '(GMT+02:00) Helsinki');
INSERT INTO tbl_timezones (identifier, description) VALUES ('Europe/Istanbul', '(GMT+02:00) Istanbul');
INSERT INTO tbl_timezones (identifier, description) VALUES ('Asia/Jerusalem', '(GMT+02:00) Jerusalem');
INSERT INTO tbl_timezones (identifier, description) VALUES ('Europe/Kiev', '(GMT+02:00) Kyiv');
INSERT INTO tbl_timezones (identifier, description) VALUES ('Europe/Minsk', '(GMT+02:00) Minsk');
INSERT INTO tbl_timezones (identifier, description) VALUES ('Europe/Riga', '(GMT+02:00) Riga');
INSERT INTO tbl_timezones (identifier, description) VALUES ('Europe/Sofia', '(GMT+02:00) Sofia');
INSERT INTO tbl_timezones (identifier, description) VALUES ('Europe/Tallinn', '(GMT+02:00) Tallinn');
INSERT INTO tbl_timezones (identifier, description) VALUES ('Europe/Vilnius', '(GMT+02:00) Vilnius');
INSERT INTO tbl_timezones (identifier, description) VALUES ('Asia/Baghdad', '(GMT+03:00) Baghdad');
INSERT INTO tbl_timezones (identifier, description) VALUES ('Asia/Kuwait', '(GMT+03:00) Kuwait');
INSERT INTO tbl_timezones (identifier, description) VALUES ('Africa/Nairobi', '(GMT+03:00) Nairobi');
INSERT INTO tbl_timezones (identifier, description) VALUES ('Asia/Riyadh', '(GMT+03:00) Riyadh');
INSERT INTO tbl_timezones (identifier, description) VALUES ('Europe/Moscow', '(GMT+03:00) Moscow');
INSERT INTO tbl_timezones (identifier, description) VALUES ('Asia/Tehran', '(GMT+03:30) Tehran');
INSERT INTO tbl_timezones (identifier, description) VALUES ('Asia/Baku', '(GMT+04:00) Baku');
INSERT INTO tbl_timezones (identifier, description) VALUES ('Europe/Volgograd', '(GMT+04:00) Volgograd');
INSERT INTO tbl_timezones (identifier, description) VALUES ('Asia/Muscat', '(GMT+04:00) Muscat');
INSERT INTO tbl_timezones (identifier, description) VALUES ('Asia/Tbilisi', '(GMT+04:00) Tbilisi');
INSERT INTO tbl_timezones (identifier, description) VALUES ('Asia/Yerevan', '(GMT+04:00) Yerevan');
INSERT INTO tbl_timezones (identifier, description) VALUES ('Asia/Kabul', '(GMT+04:30) Kabul');
INSERT INTO tbl_timezones (identifier, description) VALUES ('Asia/Karachi', '(GMT+05:00) Karachi');
INSERT INTO tbl_timezones (identifier, description) VALUES ('Asia/Tashkent', '(GMT+05:00) Tashkent');
INSERT INTO tbl_timezones (identifier, description) VALUES ('Asia/Kolkata', '(GMT+05:30) Kolkata');
INSERT INTO tbl_timezones (identifier, description) VALUES ('Asia/Kathmandu', '(GMT+05:45) Kathmandu');
INSERT INTO tbl_timezones (identifier, description) VALUES ('Asia/Yekaterinburg', '(GMT+06:00) Ekaterinburg');
INSERT INTO tbl_timezones (identifier, description) VALUES ('Asia/Almaty', '(GMT+06:00) Almaty');
INSERT INTO tbl_timezones (identifier, description) VALUES ('Asia/Dhaka', '(GMT+06:00) Dhaka');
INSERT INTO tbl_timezones (identifier, description) VALUES ('Asia/Novosibirsk', '(GMT+07:00) Novosibirsk');
INSERT INTO tbl_timezones (identifier, description) VALUES ('Asia/Bangkok', '(GMT+07:00) Bangkok');
INSERT INTO tbl_timezones (identifier, description) VALUES ('Asia/Jakarta', '(GMT+07:00) Jakarta');
INSERT INTO tbl_timezones (identifier, description) VALUES ('Asia/Krasnoyarsk', '(GMT+08:00) Krasnoyarsk');
INSERT INTO tbl_timezones (identifier, description) VALUES ('Asia/Chongqing', '(GMT+08:00) Chongqing');
INSERT INTO tbl_timezones (identifier, description) VALUES ('Asia/Hong_Kong', '(GMT+08:00) Hong Kong');
INSERT INTO tbl_timezones (identifier, description) VALUES ('Asia/Kuala_Lumpur', '(GMT+08:00) Kuala Lumpur');
INSERT INTO tbl_timezones (identifier, description) VALUES ('Australia/Perth', '(GMT+08:00) Perth');
INSERT INTO tbl_timezones (identifier, description) VALUES ('Asia/Singapore', '(GMT+08:00) Singapore');
INSERT INTO tbl_timezones (identifier, description) VALUES ('Asia/Taipei', '(GMT+08:00) Taipei');
INSERT INTO tbl_timezones (identifier, description) VALUES ('Asia/Ulaanbaatar', '(GMT+08:00) Ulaan Bataar');
INSERT INTO tbl_timezones (identifier, description) VALUES ('Asia/Urumqi', '(GMT+08:00) Urumqi');
INSERT INTO tbl_timezones (identifier, description) VALUES ('Asia/Irkutsk', '(GMT+09:00) Irkutsk');
INSERT INTO tbl_timezones (identifier, description) VALUES ('Asia/Seoul', '(GMT+09:00) Seoul');
INSERT INTO tbl_timezones (identifier, description) VALUES ('Asia/Tokyo', '(GMT+09:00) Tokyo');
INSERT INTO tbl_timezones (identifier, description) VALUES ('Australia/Adelaide', '(GMT+09:30) Adelaide');
INSERT INTO tbl_timezones (identifier, description) VALUES ('Australia/Darwin', '(GMT+09:30) Darwin');
INSERT INTO tbl_timezones (identifier, description) VALUES ('Asia/Yakutsk', '(GMT+10:00) Yakutsk');
INSERT INTO tbl_timezones (identifier, description) VALUES ('Australia/Brisbane', '(GMT+10:00) Brisbane');
INSERT INTO tbl_timezones (identifier, description) VALUES ('Australia/Canberra', '(GMT+10:00) Canberra');
INSERT INTO tbl_timezones (identifier, description) VALUES ('Pacific/Guam', '(GMT+10:00) Guam');
INSERT INTO tbl_timezones (identifier, description) VALUES ('Australia/Hobart', '(GMT+10:00) Hobart');
INSERT INTO tbl_timezones (identifier, description) VALUES ('Australia/Melbourne', '(GMT+10:00) Melbourne');
INSERT INTO tbl_timezones (identifier, description) VALUES ('Pacific/Port_Moresby', '(GMT+10:00) Port Moresby');
INSERT INTO tbl_timezones (identifier, description) VALUES ('Australia/Sydney', '(GMT+10:00) Sydney');
INSERT INTO tbl_timezones (identifier, description) VALUES ('Asia/Vladivostok', '(GMT+11:00) Vladivostok');
INSERT INTO tbl_timezones (identifier, description) VALUES ('Asia/Magadan', '(GMT+12:00) Magadan');
INSERT INTO tbl_timezones (identifier, description) VALUES ('Pacific/Auckland', '(GMT+12:00) Auckland');
INSERT INTO tbl_timezones (identifier, description) VALUES ('Pacific/Fiji', '(GMT+12:00) Fiji');
